### ISSUE TITLE
php8.2 安装后登录成功后报错  Laravel\SerializableClosure\Support\ReflectionClosure

### ISSUE THREAD

**Issue by luyilafei** [webman-php/admin#100]
Error: Class "Laravel\SerializableClosure\Support\ReflectionClosure" not found in /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/illuminate/support/Onceable.php:66
Stack trace:
#0 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/illuminate/support/Onceable.php(34): Illuminate\Support\Onceable::hashFromTrace()
#1 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/illuminate/database/Eloquent/Concerns/PreventsCircularRecursion.php(29): Illuminate\Support\Onceable::tryFromTrace()
#2 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/illuminate/database/Eloquent/Model.php(1663): Illuminate\Database\Eloquent\Model->withoutRecursion()
#3 /www/wwwroot/xyx.a.zhangyoudj.cn/plugin/admin/app/controller/AccountController.php(85): Illuminate\Database\Eloquent\Model->toArray()
#4 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/webman-framework/src/App.php(322): plugin\admin\app\controller\AccountController->login()
#5 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/webman-framework/src/App.php(352): Webman\App::Webman\{closure}()
#6 /www/wwwroot/xyx.a.zhangyoudj.cn/plugin/admin/app/middleware/AccessControl.php(47): Webman\App::Webman\{closure}()
#7 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/webman-framework/src/App.php(344): plugin\admin\app\middleware\AccessControl->process()
#8 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/webman-framework/src/App.php(169): Webman\App::Webman\{closure}()
#9 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/workerman/Connection/TcpConnection.php(646): Webman\App->onMessage()
#10 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#11 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/workerman/Worker.php(1638): Workerman\Events\Select->loop()
#12 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#13 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#14 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#15 /www/wwwroot/xyx.a.zhangyoudj.cn/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#16 /www/wwwroot/xyx.a.zhangyoudj.cn/start.php(4): support\App::run()
#17 {main} [] []

![image](https://github.com/user-attachments/assets/06d261bc-281b-4337-a298-c0521dd2dcf4)
也安装了 数据库组件 
![image](https://github.com/user-attachments/assets/e3e39728-f4d6-4d97-b365-0ea70bd70108)

**Comment by walkor** [comment]
执行下
composer require laravel/serializable-closure

最新得 illuminate/database  依赖了laravel/serializable-closure，但是他们composer.json确没定义
