### ISSUE TITLE
菜单栏能做成分模块管理的吗（顶部是一级，然后侧边栏是二级）

### ISSUE THREAD

**Issue by cshaptx4869** [webman-php/admin#15]
类似于 easyadmin 的菜单效果，顶部是一级，然后侧边栏开始是二级：
[https://foruda.gitee.com/images/1675992228886678362/5f71203a_5507348.jpeg](https://foruda.gitee.com/images/1675992228886678362/5f71203a_5507348.jpeg)
如图，像系统相关的属于系统模块菜单，商城相关的属于商城模块菜单。
如果菜单不分模块的话，那么不同模块的菜单会混合在一起，不以利查找和管理。

**Comment by walkor** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/6073368/217979863-47b8f49d-9d9e-4ab0-9867-95bd8070a1f2.png">
<img width="314" alt="image" src="https://user-images.githubusercontent.com/6073368/217979939-70ba2c30-1a4a-4161-89b4-29505df8ceab.png">

这里可以设置

**Comment by cshaptx4869** [comment]
奥奥 是我想要的 十分感谢
