### ISSUE TITLE
【BUG】修改表格时，在【字段属性】删除前面的行，【表单属性】最后一行的 【控件类型】【控件参数】会丢失

### ISSUE THREAD

**Issue by customerFirst** [webman-php/admin#47]
修改表格时，在【字段属性】删除前面的行，【表单属性】最后一行的 【控件类型】【控件参数】会丢失

**Comment by walkor** [comment]
用了layui最新版2.8？

**Comment by customerFirst** [comment]
> 用了layui最新版2.8？

后台更新升级的0.6.16版本
![微信截图_20230717104755](https://github.com/webman-php/admin/assets/30319140/852255b7-f555-49a8-8636-5fcc4f06c5af)
![微信截图_20230717104820](https://github.com/webman-php/admin/assets/30319140/1d60c7ee-cd4e-49b9-81c9-dd4f4e9671d9)

**Comment by walkor** [comment]
应该是bug，后面有时间看下。如果你解决了欢迎发pull request
