### ISSUE TITLE
后台打二进制包后  上传附件报错  

### ISSUE THREAD

**Issue by YouZiXiL** [webman-php/admin#86]
![a89e04f0c3d89d6741d9151f50e1359](https://github.com/webman-php/admin/assets/48539892/34eed8e3-1147-419a-837e-0b654c423fb6)
![04cfc5fe7b7f2bec763519b6729be6b](https://github.com/webman-php/admin/assets/48539892/c2632996-3b19-421d-a242-1962df995a25)
![image](https://github.com/webman-php/admin/assets/48539892/91cb3084-5229-4cd8-9fca-4da63f484297)

**Comment by qnnp-me** [comment]
#80 这个pr已经支持了
只需要在 `plugin/admin/config/app.php` 文件增加 `'public_path'        => base_path(false) . '/plugin/admin/public',` 即可

**Comment by YouZiXiL** [comment]
> #80 这个pr已经支持了 只需要在 `plugin/admin/config/app.php` 文件增加 `'public_path' => base_path(false) . '/plugin/admin/public',` 即可

我下载的就是最新版
![image](https://github.com/webman-php/admin/assets/48539892/c28eeea3-c83d-4a9b-8167-9168b5257ddc)

**Comment by YouZiXiL** [comment]
![image](https://github.com/webman-php/admin/assets/48539892/92657a2c-a2b7-48ca-a6ca-b09839333ebd)
看到上传文件 也有

**Comment by qnnp-me** [comment]
配置文件改了吗，加上 public 配置

**Comment by qnnp-me** [comment]
> #80 这个pr已经支持了
> 只需要在 `plugin/admin/config/app.php` 文件增加 `'public_path'        => base_path(false) . '/plugin/admin/public',` 即可

**Comment by qnnp-me** [comment]
相应的`/plugin/admin/public`文件夹你需要上传放在运行目录
