### ISSUE TITLE
由于模型基类Base设置了数据库连接导致事务操作不生效

### ISSUE THREAD

**Issue by jian1098** [webman-php/admin#94]
参照webman文档使用事务：https://www.workerman.net/doc/webman/others/transaction.html
用Db::beginTransaction();写法发现事务无法回滚，必须用Db::connection('mysql')->beginTransaction();这种加上连接的方式才有效，发现原因是后台一键菜单生成的model里面设置了protected $connection = 'plugin.admin.mysql';

是否考虑将 $connection 去掉，否则很容易掉坑里，最好是将webman-admin数据库配置与webman原本的database.php整合，必要分开两个

**Comment by walkor** [comment]
一键菜单是给 webman-admin 创建菜单、生成控制器、页面、model的，是给webman-admin插件用的，不适合用到主项目里。主项目也不应该继承插件里的基类。

如果你要给主项目创建model，应该使用 php webman make:model 命令创建。
